import styled from "@emotion/styled";
import { type StackProps } from "./Stack.types";

export const Stack = styled("div")<StackProps>`
    display: ${({ display = "flex" }) => display};
    position: ${({ position = "reltive" }) => position};
    padding: ${({ p }) => p};
    margin: ${({ m }) => m};
    top: ${({ top }) => top};
    right: ${({ right }) => right};
    bottom: ${({ bottom }) => bottom};
    left: ${({ left }) => left};
    width: ${({ width }) => width};
    height: ${({ height }) => height};
    flex-direction: ${({ direction }) => direction};
    justify-content: ${({ justifyContent }) => justifyContent};
    align-items: ${({ alignItems }) => alignItems};
    align-content: ${({ alignContent }) => alignContent};
    flex-wrap: ${({ wrap }) => wrap};
    gap: ${({ spacing }) => spacing};
    order: ${({ order }) => order};
    flex-grow: ${({ grow }) => grow};
    flex-shrink: ${({ shrink }) => shrink};
    flex-basis: ${({ basis }) => basis};
    flex: ${({ flex }) => flex};
    align-self: ${({ alignSelf }) => alignSelf};
    padding-top: ${({ pt }) => pt};
    padding-right: ${({ pr }) => pr};
    padding-bottom: ${({ pb }) => pb};
    padding-left: ${({ pl }) => pl};
    margin-top: ${({ mt }) => mt};
    margin-right: ${({ mr }) => mr};
    margin-bottom: ${({ mb }) => mb};
    margin-left: ${({ ml }) => ml};
    padding-block: ${({ py }) => py};
    padding-inline: ${({ px }) => px};
    margin-block: ${({ my }) => my};
    margin-inline: ${({ mx }) => mx};
`;
