import styled from "@emotion/styled";
import { type StackProps } from "./Stack.types";

export const Stack = styled("div")<StackProps>(
    ({
        display = "flex",
        position = "relative",
        top,
        right,
        bottom,
        left,
        width,
        height,
        direction,
        justifyContent,
        alignItems,
        alignContent,
        wrap,
        spacing,
        p,
        m,
        order,
        grow,
        shrink,
        basis,
        flex,
        alignSelf,
        pt,
        pr,
        pb,
        pl,
        mt,
        mr,
        mb,
        ml,
        py,
        px,
        my,
        mx,
    }) => ({
        display,
        position,
        padding: p,
        margin: m,
        top,
        right,
        bottom,
        left,
        width,
        height,
        flexDirection: direction,
        justifyContent,
        alignItems,
        alignContent,
        flexWrap: wrap,
        gap: spacing,
        order,
        flexGrow: grow,
        flexShrink: shrink,
        flexBasis: basis,
        flex,
        alignSelf,
        paddingTop: pt,
        paddingRight: pr,
        paddingBottom: pb,
        paddingLeft: pl,
        marginTop: mt,
        marginRight: mr,
        marginBottom: mb,
        marginLeft: ml,
        paddingBlock: py,
        paddingInline: px,
        marginBlock: my,
        marginInline: mx,
    }),
);
