import styled from "@emotion/styled";
import { variantStyles } from "./Paper.helpers";
import { PaperProps } from "./Paper.types";

export const Paper = styled.div<PaperProps>(
    ({
        theme,
        variant = "elevation",
        elevation = 0,
        color = "neutral",
        display = "flex",
        position = "relative",
        top,
        right,
        bottom,
        left,
        width,
        height,
        direction,
        justifyContent,
        alignItems,
        alignContent,
        wrap,
        spacing,
        p,
        m,
        order,
        grow,
        shrink,
        basis,
        flex,
        alignSelf,
        pt,
        pr,
        pb,
        pl,
        mt,
        mr,
        mb,
        ml,
        py,
        px,
        my,
        mx,
    }) => ({
        ...variantStyles(theme, color, elevation)[variant],
        borderRadius: "0.75rem",
        transition: "all 0.2 ease",
        display,
        position,
        top,
        right,
        bottom,
        left,
        width,
        height,
        flexDirection: direction,
        justifyContent,
        alignItems,
        alignContent,
        flexWrap: wrap,
        gap: spacing,
        padding: p,
        margin: m,
        order: order,
        flexGrow: grow,
        flexShrink: shrink,
        flexBasis: basis,
        flex,
        alignSelf: alignSelf,
        paddingTop: pt,
        paddingRight: pr,
        paddingBottom: pb,
        paddingLeft: pl,
        marginTop: mt,
        marginRight: mr,
        marginBottom: mb,
        marginLeft: ml,
        paddingBlock: py,
        paddingInline: px,
        marginBlock: my,
        marginInline: mx,
    }),
);
