import { type FC } from "react";
import { type StackProps } from "./Stack.types";

export const Stack: FC<StackProps> = ({
    display = "flex",
    position = "relative",
    top,
    right,
    bottom,
    left,
    width,
    height,
    direction,
    wrap,
    justifyContent,
    alignItems,
    alignContent,
    spacing,
    p,
    m,
    order,
    grow,
    shrink,
    basis,
    flex,
    alignSelf,
    pt,
    pr,
    pb,
    pl,
    mt,
    mr,
    mb,
    ml,
    px,
    py,
    mx,
    my,
    children,
    ...props
}) => (
    <div
        css={{
            display,
            position,
            top,
            right,
            bottom,
            left,
            width,
            height,
            flexDirection: direction,
            justifyContent,
            alignItems,
            alignContent,
            flexWrap: wrap,
            gap: spacing,
            padding: p,
            margin: m,
            order,
            flexGrow: grow,
            flexShrink: shrink,
            flexBasis: basis,
            flex,
            alignSelf,
            paddingTop: pt,
            paddingRight: pr,
            paddingBottom: pb,
            paddingLeft: pl,
            marginTop: mt,
            marginRight: mr,
            marginBottom: mb,
            marginLeft: ml,
            paddingBlock: py,
            paddingInline: px,
            marginBlock: my,
            marginInline: mx,
        }}
        {...props}
    >
        {children}
    </div>
);
